### ISSUE TITLE
Inline collapsible blocks look off and are unreadable due to an offset

### ISSUE THREAD

**Issue by zaidhaan** [gwern/gwern.net#10]
This issue is about two bugs:
1. Inline unopened collapsible previews are not visible
2. Inline opened collapsibles are not readable due to an offset

Here's an affected page: https://gwern.net/death-note-script

Search `The settings` to get to the collapsible in question.

(Note that the screen width should be wide enough such that it displays inline, as this only occurs for inline collapsibles and not regular ones.)

Here's what it looks like, inline and unopened:) **[Bug no. 1]**
![image](https://github.com/gwern/gwern.net/assets/5954994/1b096fc1-aeea-411b-9063-00fa7fedda11)

And opened: **[Bug no. 2]**
![image](https://github.com/gwern/gwern.net/assets/5954994/e0722fb7-34ab-439f-8060-bba66cfc7883)

And upon inspection (take note of the `margin-left: calc(-1019px);`):
![image](https://github.com/gwern/gwern.net/assets/5954994/17881899-58e0-41e0-8744-6451b536c422)

When not displayed inline (here, in the Appendix), everything looks fine:
![image](https://github.com/gwern/gwern.net/assets/5954994/208c3322-2bbf-4af4-9820-57d02649cd24)

---

Tested on Firefox 123.0 and Chromium 122.0.6261.69 on Arch Linux.

**Comment by gwern** [comment]
Reproduced in Chromium light mode & Firefox dark-mode.

**Comment by gwern** [comment]
Should be fixed now. Please flush cache & retry.

**Comment by zaidhaan** [comment]
Yup, works. Thanks
