### ISSUE TITLE
Articles break in Pocket

### ISSUE THREAD

**Issue by danShumway** [gwern/gwern.net#12]
If you try to save http://www.gwern.net/Causality, [Pocket](https://getpocket.com) will only save the quotes from the appendix. Haven't tried it elsewhere, but it's possible this will also be a problem for screenreaders and other parsers.

I suspect this is because the site isn't using ``article`` or ``header`` tags anywhere. For example, you have:

```
<div id="header">
    <h1>Why Correlation Usually ≠ Causation: Causal Nets Cause Common Confounding</h1>
</div>
```

There's no way for Pocket (or any parser) to know that this is actually the header of the article, rather than, say, an unrelated sidebar. This is compounded because you're using repeated ``h1`` tags, so even naive document outline parsing won't help (it's totally valid to use multiple ``h1`` tags, but not many browsers, screenreaders, etc... actually pay attention to that part of the spec)

I'm not completely sure, but if you switched from ``<div id="main">`` to ``<main>``, ``<div id="header">`` to ``<header>``, and ``<div id="content">`` to ``<article>``, that might be all you need to get everything working.

**Comment by gwern** [comment]
For the most part, I am using Pandoc's defaults, and the repeated h1 tags are simply `#` headers.

As far as the edits go, I'm concerned about it breaking the CSS. I style all of main/header/content a fair bit, and your suggested edits seem to break it. Using these changes:

```.diff
diff --git a/static/css/default.css b/static/css/default.css
index 40cb6c3..dc7e8a7 100644
--- a/static/css/default.css
+++ b/static/css/default.css
@@ -16,11 +16,11 @@
         line-height: 150%; /* see A/B tests */
     }
 
-    #header {
+    header {
         margin-bottom: 15px;
     }
 
-    div#main {
+    main {
         margin-left: 0.5em;
         margin-right: 0.5em;
         border: none;
@@ -103,7 +103,7 @@
 /* Apparently, setting “overflow” on an element creates a new formatting context which fixes this. “overflow: hidden” will do this witho
ut actually changing how overflow is handled. Unfortunately, if we do that, the bullet points and numbering inexplicably disappear and we
 have to move them “inside”. Once we fix that, <li><p>…</p></li> creates two new block contexts, causing blank lines on some bullet point
s on pages like this. */
 /* Note that I’m only messing with non-section children of sections and list elements (not the lists themselves). This is because I’m as
suming you want paragraphs and lists to wrap around the TOC" */
 /* result: http://imgur.com/lhvneyP */
-div#content>:not(section), div#content section>:not(section) {
+article>:not(section), article section>:not(section) {
     overflow: auto;
 }
 
@@ -126,7 +126,7 @@ body {
     max-width: 1600px;
 }
 
-div#header h1 {
+header h1 {
     text-align: center;
     vertical-align: middle;
 }
@@ -157,7 +157,7 @@ div#disqus_thread { padding-left: 0.5em; }
 a {
     color: #303C3C; /* off-black */
 }
-div#content a { word-wrap: break-word; /* force the occasional inline URL or other long word to break at max-width */
+article a { word-wrap: break-word; /* force the occasional inline URL or other long word to break at max-width */
                  text-decoration: none;
 }
 
diff --git a/static/templates/default.html b/static/templates/default.html
index 8910164..0f53c57 100644
--- a/static/templates/default.html
+++ b/static/templates/default.html
@@ -20,7 +20,7 @@
   </head>
   <body>
 
-    <div id="main">
+    <main>
       <div id="sidebar">
         <div id="logo"><a href="/index" title="index: categorized list of articles"><img alt="Logo: a Gothic/Fraktur blackletter capital G" src="/images/logo.png" height="75" width="64" /></a></div>
 
@@ -74,11 +74,11 @@
         </script>
       </div>
 
-      <div id="header">
+      <header>
         <h1>$title$</h1>
-      </div>
+      </header>
 
-      <div id="content">
+      <article>
 
         <noscript>Please enable JavaScript for math equation rendering.</noscript>
 
@@ -91,8 +91,8 @@
 
         $body$
 
-      </div>
-    </div>
+      </article>
+    </main>
     <div id="footer">
       <p>Still bored? Then try my <a href="https://plus.google.com/103530621949492999968/posts" title="Google+ posts">Google+ news feed</a>.</p>
```

and syncing produces the following brokenness with stuff overflowing everywhere:
![xwd-149003331827503](https://cloud.githubusercontent.com/assets/352559/24114528/f036d67c-0d76-11e7-8e27-1890b922046c.png)

(Web development is a bitter mystery.)

**Comment by danShumway** [comment]
When I make the same changes locally, I'm not seeing any issues. The overflow you're seeing is roughly consistent with what I see if I make the HTML changes locally but don't apply any of your CSS changes. Off the top of my head could be a caching issue, but if that's the case I'm surprised you haven't run into it before.

Depending on how much you actually want a solution, you could also fall back on [aria roles](https://www.w3.org/TR/wai-aria/roles#landmark_roles_header):

``<div id="main">`` becomes ``<div id="main" role="main">``, and so on with the other elements. This would allow you to add the semantics without changing your actual CSS, since all of the selectors, ids, and elements themselves would remain untouched.

It's not generally recommended to use aria roles [this way](http://w3c.github.io/aria-in-html/#rule1), but at the same time... nobody other than people like me will ever actually notice or call you out on it, and I don't know where you live so what do you care? :)

The other thing to note is that I'm really just guessing that this will solve the Pocket issue; I'm working under the assumption that they pay attention to HTML semantics and correctly parse repeated ``h1`` tags per the official HTML specs. That's not a universal guarantee. If nothing else this will certainly make it easier for other web scrapers to identify main content, metadata, and keywords, and it should in theory make screen readers work better.

How much that matters? I assume you know your target audience better than I do.

**Comment by gwern** [comment]
Hm. Caching is a possibility. I did force reload but that might've not cleared out the Cloudflare cache of the CSS. I have run into issues where that has confused me in the past. I'll try remaking those changes and emptying the CF cache and check that an updated version is being served.

**Comment by gwern** [comment]
Yes, looks like it was stale CSS. I've redid the changes, checked in the W3C Validator & `tidy`, synced, flushed the CF cache, and looked around, and it seems like those changes haven't broken anything or made it invalid HTML5. Can you check if it fixes your Pocket app?

**Comment by danShumway** [comment]
Heh, close. It catches the ``article`` tag, but still reverse parses it and grabs just the one ``h1``. This isn't your fault, using multiple ``h1`` tags in a single page is valid, especially when they're nested under ``section``s.

I'll file a bug on their end, everything is fine on yours. Thanks for taking the time to look at it!

**Comment by gwern** [comment]
Great. Then I'll commit that change & close this.
