### ISSUE TITLE
Add arxiv pdf - Vaswani et al 2017 - Transformers

### ISSUE THREAD

**Issue by koenrane** [gwern/gwern.net#2]
Proposition to add pdf/link to the following line in the article _[Why Tool AIs Want to be Agent AIs](https://www.gwern.net/Tool-AI)_:

"While LSTM RNNs are the default for sequence tasks, they have occasionally been beaten by feedforward neural networks—using internal attention or “self-attention”, like the Transformer architecture (**eg Vaswani et al 2017** or Al-Rfou et al 2018)"

Add this arxiv doc:
[Attention Is All You Need](https://arxiv.org/abs/1706.03762)

**Comment by gwern** [comment]
Vaswani is already linked in the previous paragraph so that's unnecessary.
