### ISSUE TITLE
100px inline height in collapsible blocks with code in it

### ISSUE THREAD

**Issue by zaidhaan** [gwern/gwern.net#5]
In the article [Problem 14](https://www.gwern.net/Problem-14), all 7 collapsible blocks with code in them have a fixed height of 100px in them. (This does not affect the first collapsible which is a spreadsheet and not a code block).
 
```html
<pre class="sourceCode R collapse-content-wrapper" style="height: 100px;">
    <code class="sourceCode r"> ... </code>
</pre>
```

This makes it hard to read (refer to the image below, only three lines visible), removing the inline style gets rid of this.

![Image of fixed height block](https://i.imgur.com/m2iD7D8.png)

Screenshot from Mozilla Firefox 108.0.1 on Arch Linux, also tried in Chromium Version 108.0.5359.124, behaves the same.

**Comment by gwern** [comment]
Can confirm: code collapses do not uncollapse, they just continue to show the collapsed/truncated version. Bad. I've pinged Achmiz. Must be a fairly new bug, I'm sure I checked /Lorem's code collapses in December 2022.

**Comment by zaidhaan** [comment]
Might be caused by 8008c4a but I'd guess Achmiz would've already figured the cause by now.

**Comment by gwern** [comment]
He agrees, but doesn't have time right this second to fix it properly so I'm commenting it out.
