### ISSUE TITLE
Permission to copy your website/code

### ISSUE THREAD

**Issue by sacgov** [gwern/gwern.net#7]
Your website is beyond awesome.
I want to reuse the code of your website to build my own.

Permission #1
Reuse the code as is and attribute to you with a backlink.

Permission #2 
Reuse the static part of the website, change the haskell code to python/javascript. Something more extensible by others.
Haskell is awesome of course but not widely used apart from FP enthusiasts (I count myself as one. Though erlang is my choice)

Permission #3
Make the code of "permission #2" public so others can build on top of it. Under a license you prefer me to add to it for reuse.

Do let me know :)

**Comment by gwern** [comment]
The code is already under CC-0 (or as applicable for each specific file, some are licensed under other licenses), so no further permission is required. Good luck. A fully feature-complete clone of the backend may be harder than you think, however.
