### ISSUE TITLE
Problem with images on /doc/ai/nn/transformer/gpt/5/index

### ISSUE THREAD

**Issue by veilm** [gwern/gwern.net#9]
In https://gwern.net/doc/ai/nn/transformer/gpt/5/index#stanley-2023-section, when I click on any image to enlarge it, I see the base64 for the image rather than the image itself. Screenshot:
![temp](https://github.com/gwern/gwern.net/assets/57649592/04671b2e-47ca-48e0-8e72-894712ee9c04)

This is using Chromium on Arch Linux. I see the same behaviour on Firefox and Brave, though. Images on other pages work fine.

**Comment by veilm** [comment]
From what I can tell, the problem is that ``p.image-url`` is shown, which contains ``code.url``, which contains the full URL for the image, which is specified as a long string of inline base64. On other images, the URL is still always shown as part of the Copy URL button, but the URL is assumed to be short enough that the button covers the screen.

So, I guess it would make sense to either replace the ``src`` attributes of the images on that page to use local image files, or have a system for detecting them as base64 and not showing the Copy URL button in those cases.

(Apologies if what I said was dumb and inaccurate; I haven't looked at the source code in this repository, and am just judging off of what I see in DevTools.)

**Comment by gwern** [comment]
Should be fixed now, thanks.
